---
kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: node:13
    when:
      event:
        - push
        - pull_request
    commands:
      - yarn
    depends_on:
      - clone

#  - name: integration-tests
#    image: circleci/node:13-browsers
#    # We run as root, because the docker daemon
#    # no-new-priviliges flag
#    # prohibits us from running sudo
#    user: root
#    when:
#      event:
#        - push
#        - pull_request
#    depends_on:
#      - setup
#    commands:
#      # This image runs with a custom user (circleci)by default,
#      # and chrome headless doesn't work for the root user.
#      # --> Fix some file permissions before start
#      - mkdir -p /root/.config/yarn/
#      - chown -R circleci:circleci .
#      - chown -R circleci:circleci /root/
#      - su circleci
#      - MONGO_URL=mongodb://mongodb:27017/vote-integration-test REDIS_URL=redis HEADLESS=true yarn protractor

  - name: lint
    image: node:13
    when:
      event:
        - push
        - pull_request
    depends_on:
      - setup
    commands:
      - yarn lint

  - name: test
    image: node:13
    when:
      event:
        - push
        - pull_request
    depends_on:
      - setup
    commands:
      - MONGO_URL=mongodb://mongodb:27017/vote-test REDIS_URL=redis yarn mocha

  - name: build
    image: node:13
    when:
      event:
        - push
        - pull_request
      branch:
        exclude: [prod]
    depends_on:
      - setup
    commands:
      - yarn build

  - name: docker
    image: plugins/docker
    when:
      branch:
        - prod
      event: push
      status: success
    depends_on:
      #- integration-tests
      - lint
      - test
      - build
    settings:
      repo: abakus/vote
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
      build_args:
        - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}

services:
  - name: mongodb
    image: mongo:3.6

  - name: redis
    image: redis:latest
